[book]
authors = ["postmannen"]
language = "en"
multilingual = false
src = "src"
title = "ctrl"

[output.html]
git-repository-url = "https://github.com/postmannen/ctrl"
git-repository-icon = "fa-github"

[output.html.fold]
enable = false    # whether or not to enable section folding
level = 0         # the depth to start folding
